# Generated by Django 5.2.7 on 2025-10-23 02:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Barbeiro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comissao_percentual', models.DecimalField(decimal_places=2, default=50.0, max_digits=5)),
                ('ativo', models.BooleanField(default=True)),
                ('usuario', models.OneToOneField(limit_choices_to={'cargo': 'BARBEIRO'}, on_delete=django.db.models.deletion.CASCADE, related_name='perfil_barbeiro', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Barbeiro',
                'verbose_name_plural': 'Barbeiros',
            },
        ),
    ]
