# Generated by Django 5.2.7 on 2025-10-24 03:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('barbeiros', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='barbeiro',
            name='telefone',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
    ]
