# Generated by Django 5.2.7 on 2025-10-25 04:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agendamentos', '0001_initial'),
        ('servicos', '0002_servico_descricao'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='agendamento',
            options={'ordering': ['data_hora_inicio'], 'verbose_name': 'Agendamento', 'verbose_name_plural': 'Agendamentos'},
        ),
        migrations.RenameField(
            model_name='agendamento',
            old_name='data_criacao',
            new_name='criado_em',
        ),
        migrations.AlterUniqueTogether(
            name='agendamento',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='agendamento',
            name='duracao_minutos',
            field=models.PositiveSmallIntegerField(default=30, verbose_name='Duração (minutos)'),
        ),
        migrations.AddField(
            model_name='agendamento',
            name='observacoes',
            field=models.TextField(blank=True, null=True, verbose_name='Observações'),
        ),
        migrations.AddField(
            model_name='agendamento',
            name='preco_final',
            field=models.DecimalField(decimal_places=2, default=None, max_digits=6, verbose_name='Preço Cobrado'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='agendamento',
            name='data_hora_inicio',
            field=models.DateTimeField(verbose_name='Data e Hora de Início'),
        ),
        migrations.AlterField(
            model_name='agendamento',
            name='servico',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='agendamentos', to='servicos.servico'),
        ),
        migrations.AlterField(
            model_name='agendamento',
            name='status',
            field=models.CharField(choices=[('P', 'Pendente'), ('C', 'Confirmado'), ('E', 'Concluído'), ('X', 'Cancelado'), ('N', 'No-show')], default='C', max_length=1, verbose_name='Status'),
        ),
        migrations.RemoveField(
            model_name='agendamento',
            name='data_hora_fim',
        ),
    ]
