# Generated by Django 5.2.7 on 2025-10-28 00:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agendamentos', '0002_alter_agendamento_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agendamento',
            name='duracao_minutos',
            field=models.PositiveSmallIntegerField(verbose_name='Duração (minutos)'),
        ),
    ]
