# Generated by Django 5.2.7 on 2025-10-29 23:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agendamentos', '0003_alter_agendamento_duracao_minutos'),
    ]

    operations = [
        migrations.AddField(
            model_name='agendamento',
            name='data_hora_fim',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Data e Hora de Fim'),
        ),
    ]
