# Generated by Django 5.2.7 on 2025-10-24 02:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servicos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='servico',
            name='descricao',
            field=models.TextField(blank=True, max_length=500, null=True),
        ),
    ]
