# Generated by Django 5.2.7 on 2025-10-25 04:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cliente',
            options={'ordering': ['nome'], 'verbose_name': 'Cliente', 'verbose_name_plural': 'Clientes'},
        ),
        migrations.RenameField(
            model_name='cliente',
            old_name='data_cadastro',
            new_name='criado_em',
        ),
        migrations.RemoveField(
            model_name='cliente',
            name='nome_completo',
        ),
        migrations.AddField(
            model_name='cliente',
            name='data_nascimento',
            field=models.DateField(blank=True, null=True, verbose_name='Data de Nascimento'),
        ),
        migrations.AddField(
            model_name='cliente',
            name='nome',
            field=models.CharField(default=None, max_length=100, verbose_name='Nome Completo'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='cliente',
            name='email',
            field=models.EmailField(blank=True, max_length=100, null=True, verbose_name='E-mail'),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='telefone',
            field=models.CharField(help_text='Ex: (99) 99999-9999', max_length=15, verbose_name='Telefone'),
        ),
    ]
